base_config: ../base.yaml

model:
  name: cnn_transformer
  params:
    encoder_dim: 128
    num_heads: 4
    num_encoder_layers: 2
    num_decoder_layers: 2
    conv_channels: 64
    kernel_size: 7
    poly_smoothing_kernel: 5
    reconstruction_weight: 0.2
    composition_weight: 0.5

